services:
  db:
    image: "postgres"
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "12345:12345"
    volumes:
      - ./migration/0-initial-db.sql:/docker-entrypoint-initdb.d/0-docker-database-initial.sql
      - ./migration/1-user-roles.sql:/docker-entrypoint-initdb.d/1-user-roles.sql
      - ./migration/2-search-vector-trigger.sql:/docker-entrypoint-initdb.d/2-search-vector-trigger.sql
    restart: always
    command: -p 12345
