services:
  db:
    image: "postgres"
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "1234:1234"
    volumes:
      - ./migration/initial-db.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
      - ./migration/user-roles.sql:/docker-entrypoint-initdb.d/user-roles.sql
    restart: always
    command: -p 1234
